### ISSUE TITLE
Duplicate register should not be allowed

### ISSUE THREAD

**Issue by kram46** [raventeee/STSWENG#14]
Duplicate accounts should not be allowed

Tried creating two accounts with the same details, the system allowed for the creation of the two.

See recording for details.

https://user-images.githubusercontent.com/80665149/143175477-95616109-45f4-4e36-a015-f211b6b1d344.mp4

**Comment by francisCalimbas** [comment]
Added a fix

**Comment by kram46** [comment]
fixed
![image](https://user-images.githubusercontent.com/80665149/143229138-37c86152-31ee-42f9-abd9-79eca2c06526.png)
