### ISSUE TITLE
User should not be able to login/signup again when they are signed in

### ISSUE THREAD

**Issue by kram46** [raventeee/STSWENG#16]
When a user logs in, they can still login/signup using the links in the footer

See recording:

https://user-images.githubusercontent.com/80665149/143178026-91ca369a-bdf5-4782-aae9-fa6befaa256a.mp4

**Comment by francisCalimbas** [comment]
I'll fix this

**Comment by francisCalimbas** [comment]
Added a fix

**Comment by kram46** [comment]
resolved
![image](https://user-images.githubusercontent.com/80665149/143186857-486157c2-cc85-407f-af6b-b35d4b32e68c.png)
