### ISSUE TITLE
Change Go Back home to Back To Home

### ISSUE THREAD

**Issue by kram46** [raventeee/STSWENG#19]
For consistency in the login page.
![image](https://user-images.githubusercontent.com/80665149/143231279-d4b488df-9190-4a3a-9697-c4da452eeef9.png)
![image](https://user-images.githubusercontent.com/80665149/143231298-14d438f7-a76a-485f-bdb9-e4d908b8226c.png)

**Comment by carldelacruz** [comment]
![image](https://user-images.githubusercontent.com/80733791/152154107-34d34742-ec17-4984-9030-aabab0e55a0f.png)

fixed
