### ISSUE TITLE
Replace Placeholder in sign in

### ISSUE THREAD

**Issue by kram46** [raventeee/STSWENG#22]
![image](https://user-images.githubusercontent.com/80665149/151927341-60ca3e2c-c2f2-447b-b6f0-b8fae17e4313.png)

Wrong email and/or password should have unique error messages

**Comment by francisCalimbas** [comment]
Wrong password error message:
![image](https://user-images.githubusercontent.com/66287856/151939199-613fb342-eb13-474f-9fd5-ae383bf3b0e9.png)

Email error message:
![image](https://user-images.githubusercontent.com/66287856/151939315-5b538aa6-df10-418f-bb61-b8626d61dae9.png)

**Comment by francisCalimbas** [comment]
[UPDATE]
Email error message
![image](https://user-images.githubusercontent.com/66287856/152157341-0be7c524-2d18-45ed-9df4-1d8ba620e5c2.png)

Password error message
![image](https://user-images.githubusercontent.com/66287856/152157135-ebab902f-1bf5-44bb-89b6-b9e77373e323.png)
