### ISSUE TITLE
#US6 Items added to cart not reflecting in cart page

### ISSUE THREAD

**Issue by kram46** [raventeee/STSWENG#23]
![image](https://user-images.githubusercontent.com/80665149/151927963-97aea997-33cd-477c-a672-aecec67c0f86.png)
![image](https://user-images.githubusercontent.com/80665149/151927997-13d9dcf1-5598-420b-8c5b-4d7e18ff97f7.png)

**Comment by francisCalimbas** [comment]
Added a fix, added items reflects on cart page
